### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Dweez** [ButterCMS/gatsby-source-buttercms#12]
Hello

It seems that the plugin is not compatible with the use of Locales declared in the admin. Here is the error returned during the parsing:

```
Error fetching pages { data:
   { detail:
      'Please specify a locale to view for this page. For example ?locale=en' },
  status: 404,
  ...
```
I started a version that accepts an array of locales in options and which allows to filter Pages. If you want to test it:

https://github.com/Dweez/gatsby-source-buttercms/tree/page-arguments

**Comment by jakelumetta** [comment]
Thanks. We've since enhanced the source plugin to support localization. Give it a try and let us know if you have any questions / issues.
