### ISSUE TITLE
Cannot query field "allButterContentField" on type "Query"

### ISSUE THREAD

**Issue by oshuam** [ButterCMS/gatsby-source-buttercms#29]
Tried

```
const butterPostsQuery = graphql`
  query QueryAllButterContentField {
    allButterContentField {
      edges {
        node {
          key
          value
        }
      }
    }
  }
`;
```

Response:

`error  Cannot query field "allButterContentField" on type "Query"`

_allButterPost_ and _allButterPage_ work correctly, but _allButterContentField_ and _allButterCollection_ return the same error and are not available on GraphiQL.

**Comment by orlyohreally** [comment]
@oshuam This type of error may happen due to using a wrong collection key in the source plugin config. If you provide more information on how you set config options for the plugin, we could give more specific information on the issue.

**Comment by oshuam** [comment]
Thanks @orlyohreally 

It is solved now. I was not passing any key. I see that each collection that is going to be queried need to be included as in:

```
      {
            resolve: 'gatsby-source-buttercms',
            options: {
                authToken: 'MY_AUTH_TOKEN',
                contentFields: {
                    keys: [`collection-key`],
                },
            }
        },

```
Thanks!
