### ISSUE TITLE
Reaching API Payload limit with page size of 100

### ISSUE THREAD

**Issue by d-neri** [ButterCMS/gatsby-source-buttercms#39]
The default page size in this library is currently 100, and it's easy to bump into the API payload limits when retrieving content (10 MB). We forked this and reduced the page_size to 20 for now, but lowering this limit to something more reasonable and letting the pagination do the work would be ideal.

**Comment by jakelumetta** [comment]
Thanks @d-neri ! Great suggestion

**Comment by jakelumetta** [comment]
Resolved in https://github.com/ButterCMS/gatsby-source-buttercms/commit/2ea256e84e335326bcfe7ff3bd3bdd0179a6d3e5
