### ISSUE TITLE
issue with inconsistent values on type `allButterContent`

### ISSUE THREAD

**Issue by marvinjude** [ButterCMS/gatsby-source-buttercms#9]
`allButterContent` isn't working correctly.

Basically, there are conflicting field types that is causing the fields to be omitted by Graphql.  This is as a result of the inconsistent values that was used in creating nodes.

![errgql](https://user-images.githubusercontent.com/17142206/51220264-bba39600-19a1-11e9-9295-fcfdaaecd8a8.PNG)

graphql requires that nodes of same type should have values of same type else it drops the fields affected.

E.g 

Content Field 

```
{
  key: "faq_headline",
  value: "Frequently Asked Question"
}
```

Collection

```
{
  key: "faq_items"
  value: [
    {question: "", answer: ""},
    ......
  ]
}
```

Graphql won't accept those inconsistencies. value should be of same type.

**Recommended Fix**
Separating `Collection` type from `ContentField` 

i.e
allButterCollection
allButterContentField

So on the backend those types remain the same only that the plugin trys to sepate them

**Comment by marvinjude** [comment]
I'll send a PR that fixes this issue

**Comment by jakelumetta** [comment]
Thanks @marvinjude !
